### ISSUE TITLE
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

### ISSUE THREAD

**Issue by danielhyduke** [uweschmitt/pyprophet#17]
When running pyprophet 0.18.3  with the --export.mayu flag, I get this error:

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

The problem appears to be due to trying to use the pandas.DataFrame as a boolean indicator 

https://github.com/uweschmitt/pyprophet/blob/master/pyprophet/main.py#L202
```python
    
       if CONFIG.get("export.mayu"):
           if result.final_statistics:
```

In other places, the comparison's been something like:
https://github.com/uweschmitt/pyprophet/blob/master/pyprophet/main.py#L182
```python
   if result.final_statistics is not None:
```

OpenSwathWorkflow -- Complete workflow to run OpenSWATH
Version: 2.0.0 Sep 9 2015, 13:29:57, Revision: 66a7739
CENTOS 7 64-bit
python 2.7.9

**Comment by uweschmitt** [comment]
Can you send me how you call pyprophet on the command line ? I do not see why the config value should be a pandas DataFrame and checking for "not None" might be wrong.

**Comment by danielhyduke** [comment]
It's not the config value that should be a data frame, it's that the results.final_statistics is a DataFrame and pandas no longer let the DataFrame serve as a boolean in the if statement.  given that I don't know what the default value / class should be for result.final_statistics a comparison to None could be incorrect.

here's how i call pyprophet
pyprophet --delim=tab --ignore.invalid_score_columns --target.overwrite --num_processes=10 --export.mayu results.tsv

e-mail me directly if you'd like the full, or partial, results.tsv file (the file's over 1 GB)

**Comment by uweschmitt** [comment]
Sorry, I did not read carefully enough. I merged your pull request and release pyprophet 0.18.4 now. Thanks for your contribution !
